const path = require("path");
const express = require("express");
const helmet = require("helmet");
const cron = require("node-cron");
const db = require("./db");
const c = require("./config");
const { refreshProducts } = require("./refresh");
const { detectBrand, normalizeBrand, slugifyBrand } = require("./brandDetector");

const app = express();
const publicDir = path.join(__dirname, "..", "public");
const pagesDir = path.join(publicDir, "pages");
const SITE = "https://www.onedailydrop.com";

app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json());
app.use(express.static(publicDir));

const trustPages = {"/about":"about.html","/contact":"contact.html","/privacy":"privacy.html","/terms":"terms.html","/affiliate-disclosure":"affiliate-disclosure.html","/editorial-policy":"editorial-policy.html","/how-we-select-deals":"how-we-select-deals.html","/price-disclaimer":"price-disclaimer.html"};
Object.entries(trustPages).forEach(([route, file]) => app.get(route, (req, res) => res.sendFile(path.join(pagesDir, file))));

const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const slug = value => String(value || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 90) || "deal";
const dealPath = product => `/deal/${slug(product.title)}-${product.id}`;
const catPath = value => `/category/${slug(value)}`;
const brandPath = value => `/brand/${slugifyBrand(value)}`;
const money = (value, currency = "USD") => { const n = Number(value); if (!Number.isFinite(n)) return "Check latest price"; try { return new Intl.NumberFormat("en-US", { style: "currency", currency: String(currency || "USD").toUpperCase() }).format(n); } catch { return `$${n.toFixed(2)}`; } };
const clean = value => String(value || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const shortTitle = value => { const text = clean(value); return text.length <= 78 ? text : `${text.slice(0, 75).trim()}…`; };
const storeName = product => { const source = String(product.source || "").toLowerCase(); if (source.includes("amazon") || source.includes("rainforest")) return "Amazon"; if (source.includes("walmart") || source.includes("bluecart")) return "Walmart"; return product.source || "Retailer"; };
const discountPercent = product => Number(product.original_price) > Number(product.current_price) ? Math.round((1 - Number(product.current_price) / Number(product.original_price)) * 100) : 0;
const whyPicked = product => { const points = []; if (Number(product.rating) >= 4.5) points.push(`strong ${Number(product.rating).toFixed(1)}-star rating`); if (Number(product.review_count) >= 1000) points.push(`${Number(product.review_count).toLocaleString()}+ reviews`); if (Number(product.score) >= 80) points.push(`high OneDailyDrop Score of ${Math.round(Number(product.score))}`); if (discountPercent(product) > 0) points.push(`${discountPercent(product)}% verified price reduction`); return points.length ? `We selected this product for its ${points.join(", ")}.` : "We selected this product after reviewing its price, customer feedback, availability and overall value."; };

const shell = (title, description, canonical, body, schema, image = "") => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description.slice(0,160))}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description.slice(0,180))}"><meta property="og:url" content="${canonical}">${image ? `<meta property="og:image" content="${esc(image)}">` : ""}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description.slice(0,180))}"><link rel="stylesheet" href="/styles.css?v=20260722-brand"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,"\\u003c")}</script></head><body><header class="site-header"><div class="header-top"><a class="brand" href="/"><span class="brand-mark">D</span><span class="brand-copy"><strong>OneDailyDrop</strong><small>The Best Deals. Every Day.</small></span></a></div></header>${body}<footer><div><b>OneDailyDrop</b><p>The Best Deals. Every Day.</p></div><p><a href="/affiliate-disclosure">Affiliate Disclosure</a> · <a href="/price-disclaimer">Price Disclaimer</a></p></footer></body></html>`;

const productCard = (product, index = 0) => `<article class="card"><a class="image-wrap" href="${dealPath(product)}"><img src="${esc(product.image_url)}" alt="${esc(shortTitle(product.title))}"></a><div class="card-content">${index ? `<span class="rank">#${index}</span>` : ""}${product.brand ? `<a class="eyebrow" href="${brandPath(product.brand)}">${esc(product.brand)}</a>` : ""}<h3><a href="${dealPath(product)}">${esc(shortTitle(product.title))}</a></h3><p class="description">${esc(whyPicked(product))}</p><span class="price">${money(product.current_price, product.currency)}</span></div></article>`;
const findProduct = param => { const id = String(param).match(/-(\d+)$/)?.[1] || (/^\d+$/.test(param) ? param : null); return id ? db.prepare("SELECT * FROM products WHERE id=? AND status='published'").get(id) : null; };
const historyFor = id => db.prepare("SELECT price,original_price,currency,source,observed_at FROM price_history WHERE product_id=? ORDER BY observed_at ASC").all(id);
const minSince = (rows, days) => { const cutoff = Date.now() - days * 86400000; const values = rows.filter(row => new Date(row.observed_at).getTime() >= cutoff).map(row => Number(row.price)).filter(Number.isFinite); return values.length ? Math.min(...values) : null; };
const chartSvg = rows => { if (rows.length < 2) return "<p>Price tracking has started. A chart will appear after another price change is recorded.</p>"; const values = rows.map(row => Number(row.price)).filter(Number.isFinite); const min = Math.min(...values), max = Math.max(...values), range = Math.max(max - min, 1); const points = values.map((value, index) => `${20 + (index / (values.length - 1)) * 560},${180 - ((value - min) / range) * 140}`).join(" "); return `<svg viewBox="0 0 600 210" role="img" aria-label="Price history chart" style="width:100%;max-width:760px"><line x1="20" y1="180" x2="580" y2="180" stroke="currentColor" opacity=".25"/><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="4"/><text x="20" y="202" font-size="14">${esc(money(min, rows[0]?.currency))}</text><text x="500" y="24" font-size="14">${esc(money(max, rows[0]?.currency))}</text></svg>`; };

app.get("/deal/:slug", (req, res) => {
  const p = findProduct(req.params.slug);
  if (!p) return res.status(404).send("Product not found");
  if (req.path !== dealPath(p)) return res.redirect(301, dealPath(p));
  const canonical = SITE + dealPath(p), title = shortTitle(p.title), description = clean(p.description) || whyPicked(p), store = storeName(p), category = p.category || "Deals";
  const history = historyFor(p.id), allLow = history.length ? Math.min(...history.map(row => Number(row.price)).filter(Number.isFinite)) : null, low30 = minSince(history, 30), low90 = minSince(history, 90);
  const related = p.brand_slug ? db.prepare("SELECT * FROM products WHERE status='published' AND brand_slug=? AND id<>? ORDER BY score DESC LIMIT 4").all(p.brand_slug, p.id) : [];
  const productSchema = {"@context":"https://schema.org","@graph":[{"@type":"Product",name:title,brand:p.brand?{"@type":"Brand",name:p.brand}:undefined,manufacturer:p.manufacturer?{"@type":"Organization",name:p.manufacturer}:undefined,mpn:p.mpn||undefined,gtin:p.gtin||p.ean||p.upc||undefined,image:p.image_url?[p.image_url]:undefined,description,aggregateRating:Number(p.rating)?{"@type":"AggregateRating",ratingValue:Number(p.rating),reviewCount:Number(p.review_count||0)}:undefined,offers:{"@type":"Offer",url:canonical,priceCurrency:String(p.currency||"USD").toUpperCase(),price:Number(p.current_price)||undefined,availability:"https://schema.org/InStock",seller:{"@type":"Organization",name:store}}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE},{"@type":"ListItem",position:2,name:category,item:SITE+catPath(category)},...(p.brand?[{"@type":"ListItem",position:3,name:p.brand,item:SITE+brandPath(p.brand)}]:[]),{"@type":"ListItem",position:p.brand?4:3,name:title,item:canonical}]}]};
  const brandBlock = p.brand ? `<p class="eyebrow">Brand: <a href="${brandPath(p.brand)}">${esc(p.brand)}</a></p>` : `<p class="eyebrow">${esc(store)}</p>`;
  const relatedBlock = related.length ? `<section class="deals-section"><div class="section-heading"><div><p class="eyebrow">MORE FROM THIS BRAND</p><h2>More ${esc(p.brand)} deals</h2></div><a href="${brandPath(p.brand)}">View all →</a></div><div class="grid">${related.map(product => productCard(product)).join("")}</div></section>` : "";
  const body = `<main class="product-page"><nav class="breadcrumb"><a href="/">Home</a><span>›</span><a href="${catPath(category)}">${esc(category)}</a>${p.brand?`<span>›</span><a href="${brandPath(p.brand)}">${esc(p.brand)}</a>`:""}<span>›</span><span>${esc(title)}</span></nav><article class="product-detail"><div class="product-detail-media"><img src="${esc(p.image_url)}" alt="${esc(title)}"></div><div class="product-detail-content">${brandBlock}<h1>${esc(title)}</h1><div class="product-score"><strong>${Math.round(Number(p.score)||0)}/100</strong><span>OneDailyDrop Score</span></div><p class="product-lead">${esc(description)}</p><section class="editorial-box"><h2>Why we picked it</h2><p>${esc(whyPicked(p))}</p></section><div class="detail-grid"><section><h3>Current price</h3><p>${money(p.current_price,p.currency)}</p></section><section><h3>30-day low</h3><p>${money(low30,p.currency)}</p></section><section><h3>90-day low</h3><p>${money(low90,p.currency)}</p></section><section><h3>All-time tracked low</h3><p>${money(allLow,p.currency)}</p></section></div><section class="editorial-box"><h2>Price history</h2>${chartSvg(history)}<p>${history.length} tracked price observation${history.length===1?"":"s"}.</p></section><div class="product-price-box"><span class="product-price">${money(p.current_price,p.currency)}</span>${p.original_price?`<span class="old">${money(p.original_price,p.currency)}</span>`:""}<small>Final price is confirmed on the retailer website.</small></div><a class="featured-button" href="/go/${p.id}" rel="nofollow sponsored">See deal on ${esc(store)} →</a></div></article>${relatedBlock}</main>`;
  res.send(shell(`${title} | OneDailyDrop`, description, canonical, body, productSchema, p.image_url));
});

app.get("/category/:slug", (req, res) => {
  const all = db.prepare("SELECT * FROM products WHERE status='published' ORDER BY score DESC,updated_at DESC").all();
  const category = [...new Set(all.map(product => product.category).filter(Boolean))].find(value => slug(value) === req.params.slug);
  if (!category) return res.status(404).send("Category not found");
  const products = all.filter(product => product.category === category), canonical = SITE + catPath(category), description = `Browse the best ${category} deals selected by OneDailyDrop.`;
  const schema = {"@context":"https://schema.org","@type":"ItemList",name:`Best ${category} Deals`,itemListElement:products.map((product,index)=>({"@type":"ListItem",position:index+1,url:SITE+dealPath(product),name:shortTitle(product.title)}))};
  res.send(shell(`Best ${category} Deals | OneDailyDrop`, description, canonical, `<main><section class="deals-section"><div class="section-heading"><div><p class="eyebrow">CATEGORY</p><h1>${esc(category)} Deals</h1></div><p class="result-count">${products.length} products</p></div><div class="grid">${products.map((product,index)=>productCard(product,index+1)).join("")}</div></section></main>`, schema));
});

app.get("/brand/:slug", (req, res) => {
  const products = db.prepare("SELECT * FROM products WHERE status='published' AND brand_slug=? ORDER BY score DESC,updated_at DESC").all(req.params.slug);
  if (!products.length) return res.status(404).send("Brand not found");
  const brand = products[0].brand, canonical = SITE + brandPath(brand), avgPrice = products.reduce((sum,p)=>sum+Number(p.current_price||0),0)/products.length, avgRating = products.reduce((sum,p)=>sum+Number(p.rating||0),0)/products.length, avgDiscount = products.reduce((sum,p)=>sum+discountPercent(p),0)/products.length;
  const description = `Browse ${products.length} ${brand} deals, price drops and top-rated products selected by OneDailyDrop.`;
  const schema = {"@context":"https://schema.org","@graph":[{"@type":"Brand",name:brand,url:canonical},{"@type":"ItemList",name:`Best ${brand} Deals`,itemListElement:products.map((product,index)=>({"@type":"ListItem",position:index+1,url:SITE+dealPath(product),name:shortTitle(product.title)}))},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:SITE},{"@type":"ListItem",position:2,name:"Brands",item:SITE+"/brands"},{"@type":"ListItem",position:3,name:brand,item:canonical}]}]};
  const stats = `<div class="detail-grid"><section><h3>Products</h3><p>${products.length}</p></section><section><h3>Average price</h3><p>${money(avgPrice,products[0].currency)}</p></section><section><h3>Average rating</h3><p>${avgRating.toFixed(1)} / 5</p></section><section><h3>Average discount</h3><p>${Math.round(avgDiscount)}%</p></section></div>`;
  res.send(shell(`${brand} Deals & Price Drops | OneDailyDrop`, description, canonical, `<main><section class="deals-section"><nav class="breadcrumb"><a href="/">Home</a><span>›</span><a href="/brands">Brands</a><span>›</span><span>${esc(brand)}</span></nav><div class="section-heading"><div><p class="eyebrow">BRAND</p><h1>${esc(brand)} Deals</h1><p>${esc(description)}</p></div></div>${stats}<div class="grid">${products.map((product,index)=>productCard(product,index+1)).join("")}</div></section></main>`, schema));
});

app.get("/brands", (req, res) => {
  const brands = db.prepare("SELECT brand,brand_slug,COUNT(*) product_count,AVG(current_price) avg_price,AVG(rating) avg_rating FROM products WHERE status='published' AND brand_slug<>'' GROUP BY brand,brand_slug ORDER BY product_count DESC,brand ASC").all();
  const canonical = SITE + "/brands", description = "Explore popular brands and their best current deals on OneDailyDrop.";
  const schema = {"@context":"https://schema.org","@type":"ItemList",name:"Popular Brands",itemListElement:brands.map((brand,index)=>({"@type":"ListItem",position:index+1,url:SITE+brandPath(brand.brand),name:brand.brand}))};
  const cards = brands.map(brand => `<article class="card"><div class="card-content"><p class="eyebrow">${brand.product_count} DEALS</p><h2><a href="${brandPath(brand.brand)}">${esc(brand.brand)}</a></h2><p>Average price ${money(brand.avg_price)} · Rating ${Number(brand.avg_rating||0).toFixed(1)}</p></div></article>`).join("");
  res.send(shell("Popular Brands & Deals | OneDailyDrop", description, canonical, `<main><section class="deals-section"><div class="section-heading"><div><p class="eyebrow">BRANDS</p><h1>Popular Brands</h1></div><p class="result-count">${brands.length} brands</p></div><div class="grid">${cards}</div></section></main>`, schema));
});

app.get("/robots.txt", (req, res) => res.type("text/plain").send(`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /api/\nSitemap: ${SITE}/sitemap.xml\n`));
app.get("/sitemap.xml", (req, res) => { const products = db.prepare("SELECT id,title,category,brand,brand_slug,updated_at FROM products WHERE status='published'").all(), categories = [...new Set(products.map(p=>p.category).filter(Boolean))], brands = [...new Map(products.filter(p=>p.brand_slug).map(p=>[p.brand_slug,p.brand])).values()], staticUrls = ["/","/brands",...Object.keys(trustPages)]; const urls = [...staticUrls.map(loc=>({loc:SITE+loc})),...categories.map(value=>({loc:SITE+catPath(value)})),...brands.map(value=>({loc:SITE+brandPath(value)})),...products.map(product=>({loc:SITE+dealPath(product),lastmod:product.updated_at}))]; res.type("application/xml").send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(item=>`<url><loc>${esc(item.loc)}</loc>${item.lastmod?`<lastmod>${new Date(item.lastmod).toISOString()}</lastmod>`:""}</url>`).join("")}</urlset>`); });

const admin = (req,res,next) => (req.headers["x-admin-key"] || req.query.key) === c.adminKey ? next() : res.status(401).json({error:"Unauthorized"});
app.get("/api/products", (req, res) => { const params = [], conditions = ["status='published'"]; if (req.query.brand) { conditions.push("brand_slug=?"); params.push(slugifyBrand(req.query.brand)); } if (req.query.category) { conditions.push("category=?"); params.push(String(req.query.category)); } const products = db.prepare(`SELECT * FROM products WHERE ${conditions.join(" AND ")} ORDER BY score DESC,updated_at DESC`).all(...params); res.json(products.map(product=>({...product,slug:slug(product.title),deal_url:dealPath(product),category_url:catPath(product.category||"deals"),brand_url:product.brand?brandPath(product.brand):null}))); });
app.get("/api/brands", (req,res) => res.json(db.prepare("SELECT brand,brand_slug,COUNT(*) product_count,AVG(current_price) avg_price,AVG(rating) avg_rating,AVG(CASE WHEN original_price>current_price THEN (1-current_price/original_price)*100 ELSE 0 END) avg_discount FROM products WHERE status='published' AND brand_slug<>'' GROUP BY brand,brand_slug ORDER BY product_count DESC,brand ASC").all().map(brand=>({...brand,url:brandPath(brand.brand)}))));
app.get("/api/brands/:slug", (req,res) => { const products = db.prepare("SELECT * FROM products WHERE status='published' AND brand_slug=? ORDER BY score DESC").all(req.params.slug); if (!products.length) return res.status(404).json({error:"Brand not found"}); const brand = products[0].brand; res.json({brand,slug:req.params.slug,url:brandPath(brand),summary:{products:products.length,average_price:products.reduce((s,p)=>s+Number(p.current_price||0),0)/products.length,average_rating:products.reduce((s,p)=>s+Number(p.rating||0),0)/products.length,average_discount:products.reduce((s,p)=>s+discountPercent(p),0)/products.length,total_clicks:db.prepare("SELECT COUNT(*) n FROM clicks c JOIN products p ON p.id=c.product_id WHERE p.brand_slug=?").get(req.params.slug).n},products:products.map(p=>({...p,deal_url:dealPath(p)}))}); });
app.get("/api/products/:id/price-history", (req,res) => { const product = db.prepare("SELECT id,title,current_price,currency FROM products WHERE id=? AND status='published'").get(req.params.id); if (!product) return res.status(404).json({error:"Product not found"}); const history = historyFor(product.id); res.json({product,summary:{observations:history.length,lowest_30_days:minSince(history,30),lowest_90_days:minSince(history,90),lowest_ever:history.length?Math.min(...history.map(row=>Number(row.price)).filter(Number.isFinite)):null},history}); });
app.get("/api/status", (req,res) => res.json({provider:c.provider,products:db.prepare("SELECT COUNT(*) n FROM products WHERE status='published'").get().n,brands:db.prepare("SELECT COUNT(DISTINCT brand_slug) n FROM products WHERE status='published' AND brand_slug<>''").get().n,clicks:db.prepare("SELECT COUNT(*) n FROM clicks").get().n,priceObservations:db.prepare("SELECT COUNT(*) n FROM price_history").get().n,lastRun:db.prepare("SELECT * FROM refresh_runs ORDER BY id DESC LIMIT 1").get()}));
app.post("/api/admin/refresh", admin, async (req,res) => { try { res.json(await refreshProducts(c)); } catch (error) { res.status(500).json({error:error.message}); } });
app.get("/go/:id", (req,res) => { const product = db.prepare("SELECT * FROM products WHERE id=? AND status='published'").get(req.params.id); if (!product) return res.sendStatus(404); db.prepare("INSERT INTO clicks(product_id,clicked_at,referrer,user_agent) VALUES(?,?,?,?)").run(product.id,new Date().toISOString(),req.get("referer")||"",req.get("user-agent")||""); res.redirect(302,product.affiliate_url); });
app.get("/admin", (req,res) => res.sendFile(path.join(publicDir,"admin.html")));

function backfillBrands() {
  const rows = db.prepare("SELECT id,title,description,brand,manufacturer FROM products WHERE status='published' AND (brand_slug IS NULL OR brand_slug='')").all();
  const update = db.prepare("UPDATE products SET brand=?,brand_slug=? WHERE id=?");
  db.transaction(() => { for (const row of rows) { const brand = normalizeBrand(detectBrand(row)); if (brand) update.run(brand, slugifyBrand(brand), row.id); } })();
  if (rows.length) console.log(`Brand intelligence reviewed ${rows.length} existing products`);
}

cron.schedule(c.refreshCron, () => refreshProducts(c).catch(error => console.error(error.message)), {timezone:c.timezone});
(async () => { backfillBrands(); if (!db.prepare("SELECT COUNT(*) n FROM products WHERE status='published'").get().n) await refreshProducts(c).catch(console.error); app.listen(c.port, () => console.log(`http://localhost:${c.port}`)); })();
